### PR TITLE
remove cockroach zone configuration

### PR DESCRIPTION
**Pull request by thisisibrahimd**
Removed the cockroach database configuration and automate it in the helm-charts repo (https://github.com/ScoreTrak/helm-charts/pull/21).

### CODE REVIEW

**Comment by L1ghtman2k** [comment]
I am liking this, but let's add some way to warn in logs that missing this setting would lead to an undesirable behavior

**Comment by thisisibrahimd** [comment]
> I am liking this, but let's add some way to warn in logs that missing this setting would lead to an undesirable behavior

Will add an warning in the master command.
Would it be better to optimize how the report is stored since that is the source of the problem?

**Comment by L1ghtman2k** [comment]
I agree, that might be a better overall solution. The problem is that we write too much data in and out, yes. If a single row could hold less data, that would be ideal.

**Comment by thisisibrahimd** [comment]
This is not an ideal solution but this shall do for now.

**Pull request closed without merging**
