### PR TITLE
only copy over the queue information to the worker static config

### PR DESCRIPTION
**Pull request by thisisibrahimd**

### CODE REVIEW

**Comment by L1ghtman2k** [comment]
LGTM

**Comment by thisisibrahimd** [comment]
I am getting errors when deploying to non default namespaces. The daemonsets are only getting deployed to default namespace.

**Comment by L1ghtman2k** [comment]
> I am getting errors when deploying to non default namespaces. The daemonsets are only getting deployed to default namespace.

This might not be related to this issue? I don't think worker CFG decides where workers get deployed. I think this is just how app behaved all along, and we could track this as a separate issue

**Comment by L1ghtman2k** [comment]
Hm, interesting app has access to deploy to other namespaces,  Perhaps we can downgrade perms from cluster role, to role for this one

**Comment by thisisibrahimd** [comment]
It might not be related to this issue, but an interesting issue for sure. I am assuming it was never deployed in a non default namespace for lockdown because nsq would not work at all.
Though, the cfg from the master cfg.platform.namespace is used to decide namespace meta object for daemonset spec and pod spec. 

Will decrease the perms for cluster role then.

**Comment by L1ghtman2k** [comment]
I think we can do following:
 - Allow overwriting namespace field for workers, but by default deploy it in the same namespace as mater

**Comment by L1ghtman2k** [comment]
https://github.com/ScoreTrak/ScoreTrak/pull/312

**Comment by thisisibrahimd** [comment]
good to go.

**Pull request merged**
