### PR TITLE
3 implement code coverage analysis utility

### PR DESCRIPTION
**Pull request by thisisibrahimd**

### CODE REVIEW

**Comment by thisisibrahimd** [comment]
not sure if we want to remove .github/workflows/testing.yml

**Comment by L1ghtman2k** [comment]
> not sure if we want to remove .github/workflows/testing.yml

I think that would be fine, if codecov is handling it

**Comment by thisisibrahimd** [comment]
tests were failing because github actions would lowercase the true value of AUTO_TEST env var but the test would check for the capitalized TRUE. :(

**Comment by thisisibrahimd** [comment]
Added support for sqlite db testing.
Removed parallel testing that multiple test interacting with the scoretrak.db file would cause unintended side effects.

**Comment by thisisibrahimd** [comment]
Tests are running successfully with access to the database but failing. Need to fix tests to pass 🥲.

**Comment by L1ghtman2k** [comment]
@dependabot rebase

**Comment by thisisibrahimd** [comment]
tests are working and passing with linting issues gone.

**Pull request merged**
